name: Main Taski workflow

on:
  push:
    branches:
      - main
  
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: checkout@v4
      -name: Set up python
       uses: actions/setup-python
       with:
        python-version: "3.10"
      - name: pip install
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff
      - name: Lint with ruff
        run: python -m ruff check backend/
