name: Main Taski workflow

on:
  push:
    branches:
      - main
  
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    # Копируем код проекта
    - name: Check out code
      uses: actions/checkout@v4
    # Устанавливаем Python с помощью action
    - name: Set up Python
      uses: actions/setup-python@v5
    # В action setup-python передаём параметр — версию Python
      with:
        python-version: "3.10"
    # Обновляем pip, устанавливаем ruff
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install ruff==0.8.0
        pip install -r ./backend/requirements.txt
    # Запускаем ruff
    - name: Lint with ruff and tests
      # Вызываем ruff и указываем ему,
      # что нужно проверить файлы только в папке backend/
      run: |
        python -m ruff check backend/
        cd backend/
        python manage.py test
